drop table if exists book;
drop table if exists person;

-- CREATE TABLE IF NOT EXISTS mytable

create table person
(
    person_id        integer generated by default as identity
        primary key,
    full_name        varchar(100) not null
        unique
        constraint person_full_name_check
            check (char_length((full_name)::text) >= 8),
    year_of_birthday integer      not null
        constraint person_year_of_birthday_check
            check (year_of_birthday > 0),
    password         varchar,
    login            varchar,
    role             varchar
);

create table book
(
    book_id         integer generated by default as identity
        primary key,
    person_id       integer
                                 references person
                                     on delete set null,
    title           varchar(100) not null,
    year_of_realise integer      not null
        constraint book_year_of_realise_check
            check (year_of_realise > 0),
    author          varchar(50)  not null,
    taken_at        timestamp
);

insert into person(person_id,full_name,year_of_birthday,password,login,role) values
(1,'Петров Новый Петрович',2010,'$2a$10$/8DrxTG6yiPC7QdyJFlu3OON8N2IekstYla/vIOg.Fvebs/oH.8ea','user','ROLE_ADMIN'),
(2,'Никонов Иван Вениаминович',1991,'$2a$10$htNiuCitNrrP0KFmFoV9M.IJKbBRBygCh8lKbvUwrK5yClYB0NL3W','user2','ROLE_USER');

insert into book(book_id,person_id,title,year_of_realise,author,taken_at) values
(3,1,'Основы программирования',1999,'Стив Джобс', now()),
(2,2,'Очаровательный кишечник',2019,'Элизабет Тейлор', now()),
(4,null,'Инвестиции в будущее',2010,'Элизабет Тейлор', null);